my_blog/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.article_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.article_list, name='post_list_by_tag'),
    path('about/', views.about, name='blog_about'),
    path('search/', views.search, name='blog_search'),
    path('mdeditor/', include('mdeditor.urls')),
    path('archive/', views.archive, name='archive')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_blog.urls', namespace='blog')),
]

my_blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager
from mdeditor.fields import MDTextField

# Create your models here.


class ArticleManager(models.Manager):
    def distinct_date(self):
        archive_list = []
        # .values 是把所有日期取出来
        for date in self.filter(status='published').values('publish'):
            # 上面取出来的值是 字典
            # 然后把日期格式化为 年月
            date = date['publish'].strftime('%Y%m')
            # 日期去重
            # 如果格式化后的日期不在列表中，则把它添加至列表中
            if date not in archive_list:
                archive_list.append(date)
        # 列表反转
        archive_list.sort(reverse=True)
        return archive_list


class Category(models.Model):
    name = models.CharField(max_length=64)


class Article(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None)
    objects = ArticleManager()

    class Meta:
        # verbose_name = "文章"
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=64)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

my_blog/forms.py
from .models import Comment
from django import forms

from mdeditor.fields import MDTextFormField


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


# class CommentForm(forms.Form):
#     name = forms.CharField(label='y_name', max_length=100)
#     email = forms.EmailField()
#     body = MDTextFormField()

my_blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Article, Comment
from .forms import CommentForm

from taggit.models import Tag
import markdown

# Create your views here.


def article_list(request, tag_slug=None):
    # 获取所有文章
    # object_list = Article.objects.all()
    # 获取 status='published' 的文章，使用 filter 方法
    object_list = Article.objects.filter(status='published')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    # 获取所有标签
    tags = Article.tags.all()

    # 文章归档功能实现
    # 获取所有时间
    dates = Article.objects.distinct_date()
    print(dates)

    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag, 'tags': tags, 'dates': dates})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Article, slug=post, status="published", publish__year=year, publish__month=month,
                             publish__day=day)

    # 将 markdown 语法渲染成 HTML 样式
    post.body = markdown.markdown(post.body, extensions=[
        # 添加拓展
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})


def about(request):
    return render(request, 'blog/about.html')


def search(request):
    query_set = set()
    if request.method == "GET":
        keyword = request.GET.get('keyword')
        # 判断 keyword 是否为空或者空格，是的话重定向到首页
        if not keyword or keyword.isspace():
            # redirect 重定向
            return redirect('/')
        else:
            object_list = Article.objects.filter(status="published")
            # 查询 title，使用 title__icontains ,意为查询 title 中是否含有 keyword，大小写不敏感
            for i in object_list.filter(title__icontains=keyword):
                query_set.add(i)
            # 查询 body
            for i in object_list.filter(body__icontains=keyword):
                query_set.add(i)
            # 后期可以搞下分页
    return render(request, 'blog/search.html', {'posts': query_set})


def archive(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    archives = Article.objects.filter(publish__year=year, publish__month=month)
    return render(request, 'blog/archive.html', {'posts':archives})

templates/blog/about.html
<!DOCTYPE html>
<html lang="zh-hans">

<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>

<body>
    <h1>一只二维世界的鱼。</h1>
</body>

</html>

templates/blog/archive.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<div class="article">
    {% for post in posts %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h4>
    {% endfor %}
</div>
{% endblock %}

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/comment.css' %}" rel="stylesheet">
    <link href="{% static 'css/code.css' %}" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
    <style>
        .navbar {
            position: relative;
            min-height: 50px;
            margin-bottom: 20px;
            border: 1px solid transparent;
        }

        .footer {
            bottom: 0;
            width: 100%;
            height: 50px;
            line-height: 50px;
            background: #f8f8f8;
            text-align: center;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:post_list'%}">My Blog</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'blog:post_list'%}">Home</a></li>
                    <li><a href="{% url 'blog:blog_about'%}">About</a></li>
                    <li class="contact"><a href="#">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Categories <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Python</a></li>
                            <li><a href="#">Django</a></li>
                            <li><a href="#">Vue</a></li>
<!--                            <li role="separator" class="divider"></li>-->
<!--                            <li class="dropdown-header">Nav header</li>-->
<!--                            <li><a href="#">Separated link</a></li>-->
<!--                            <li><a href="#">One more separated link</a></li>-->
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
<!--                    <li><a href="#">Register</a></li>-->
<!--                    <li><a href="#">Login</a></li>-->
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}

    </div>
    <div class="footer">
            <p>Copyright © 2019 斜风细雨不须归</p>
        </div>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
</body>

</html>

templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<div>
    <h1>{{ post.title }}</h1>
    <br>
    <p>
        Published {{ post.publish }} by {{ post.author }}
    </p>
    <br>
    {{ post.body|safe}}
</div>
{% with comments.count as total_comments %}
    <h2>
        共有{{ total_comments }}条评论：
    </h2>
{% endwith %}
{% for comment in comments %}
    <div class="comment">
        {{ comment.body|linebreaks }}
        <div class="body">
            <p class="info">
            {{ forloop.counter }}楼 by {{ comment.name }}
            {{ comment.created |date:"Y-m-d H:i" }}
            </p>
        </div>
    </div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>发表评论</h2>
    <form action="." method="post">
    <div>
        {{ comment_form.media }}
        {{ comment_form.as_p }}
    </div>
    {% csrf_token %}
    <p><input type="submit" value="提交评论"></p>
    </form>
{% endif %}
{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<div class="row">
    <div class="col-sm-8 blog-main">
        <div class="article">
            {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="tag">
                Tags:
                {% for tag in post.tags.all %}
                <span class="label label-success"><a
                        href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a></span>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">
                Published {{ post.publish |date:"Y-m-d H:i"}} by {{ post.author }}
            </p>
            {{ post.body|truncatewords:"200"|linebreaks|slice:"200" }}
            {% endfor %}
        </div>
        {% include 'pagination.html' with page=posts %}
    </div>
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="input-group">
            <form class="form-inline" action="{% url 'blog:blog_search'%}" method="get">
                <input type="text" class="form-control" placeholder="Search for..." name="keyword">
                <input type="submit" value="Go!">
                <!--                <span class="input-group-btn">-->
                <!--                    <button class="btn btn-default" type="button">Go!</button>-->
                <!--                </span>-->
            </form>
        </div>
        <br>
        <div class="panel panel-default">
            <div class="panel-heading">标签</div>
            <div class="panel-body">
                {% for tag in tags %}
                <p><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></p>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">文章归档</div>
            <div class="panel-body">
                {% for date in dates %}
                <p><a href="{% url 'blog:archive'%}?year={{date|slice:':4'}}&month={{date|slice:'4:'}}">{{date|slice:':4'}}年{{date|slice:'4:'}}月文章</a></p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/search.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>一共查询到{{ posts | length }}条结果。</h1>
<div class="article">
    {% for post in posts %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h4>
    {% endfor %}
</div>
{% endblock %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>